// GitHub REST API helpers — OAuth token exchange + Git Data API bulk push.

const GITHUB_API = 'https://api.github.com';
const USER_AGENT = 'BuilderPro/1.0';

type GithubResult<T> = { ok: true; data: T } | { ok: false; status: number; message: string };

async function githubRequest<T>(
	token: string,
	method: string,
	path: string,
	body?: unknown
): Promise<GithubResult<T>> {
	const res = await fetch(`${GITHUB_API}${path}`, {
		method,
		headers: {
			Authorization: `Bearer ${token}`,
			Accept: 'application/vnd.github+json',
			'X-GitHub-Api-Version': '2022-11-28',
			'Content-Type': 'application/json',
			'User-Agent': USER_AGENT
		},
		...(body !== undefined ? { body: JSON.stringify(body) } : {})
	});

	if (res.ok) {
		const data = res.status === 204 ? ({} as T) : ((await res.json()) as T);
		return { ok: true, data };
	}

	const err = (await res.json().catch(() => ({ message: res.statusText }))) as { message?: string };
	return { ok: false, status: res.status, message: err.message ?? 'GitHub API error' };
}

export function generateOAuthState(): string {
	const bytes = crypto.getRandomValues(new Uint8Array(32));
	return Array.from(bytes)
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
}

/** Exchange an OAuth authorization code for an access token. */
export async function exchangeCode(
	code: string,
	clientId: string,
	clientSecret: string
): Promise<string | null> {
	const res = await fetch('https://github.com/login/oauth/access_token', {
		method: 'POST',
		headers: {
			Accept: 'application/json',
			'Content-Type': 'application/json',
			'User-Agent': USER_AGENT
		},
		body: JSON.stringify({ client_id: clientId, client_secret: clientSecret, code })
	});

	if (!res.ok) return null;
	const data = (await res.json()) as { access_token?: string };
	return data.access_token ?? null;
}

/** Fetch the authenticated GitHub user's login name. */
export async function getGithubUser(token: string): Promise<{ login: string } | null> {
	const result = await githubRequest<{ login: string }>(token, 'GET', '/user');
	return result.ok ? result.data : null;
}

export interface FileContent {
	path: string;
	content: string;
}

/**
 * Push files to a GitHub repo using the Git Data API (single commit, all files at once).
 * Creates the repo if it doesn't exist. Always replaces the full tree.
 * Handles empty repos (no git storage) by initializing via Contents API first.
 */
export async function pushFilesToRepo(
	token: string,
	owner: string,
	repoName: string,
	files: FileContent[],
	commitMessage: string
): Promise<{ repoUrl: string } | { error: string }> {
	const repoPath = `/repos/${owner}/${repoName}`;

	// 1. Ensure repo exists — create with auto_init so git storage is ready.
	let defaultBranch: string;
	const repoCheck = await githubRequest<{ default_branch: string }>(token, 'GET', repoPath);
	if (!repoCheck.ok) {
		if (repoCheck.status !== 404) return { error: repoCheck.message };
		const created = await githubRequest<{ default_branch: string }>(token, 'POST', '/user/repos', {
			name: repoName,
			private: false,
			auto_init: true,
			description: 'Generated by BuilderPro'
		});
		if (!created.ok) return { error: created.message };
		defaultBranch = created.data.default_branch ?? 'main';
	} else {
		defaultBranch = repoCheck.data.default_branch;
	}

	// 2. Get current HEAD — if repo is empty (legacy repos created without auto_init),
	//    initialize git storage via Contents API before using Git Data API.
	let parentSha: string | undefined;
	const headResult = await githubRequest<{ object: { sha: string } }>(
		token,
		'GET',
		`${repoPath}/git/refs/heads/${defaultBranch}`
	);
	if (headResult.ok) {
		parentSha = headResult.data.object.sha;
	} else {
		// No refs: git storage not initialized. Use Contents API to create first commit.
		const initResult = await githubRequest<{ commit: { sha: string } }>(
			token,
			'PUT',
			`${repoPath}/contents/.gitkeep`,
			{ message: 'Initialize repository', content: 'Cg==' } // base64 of '\n'
		);
		if (!initResult.ok)
			return { error: (initResult as { ok: false; message: string }).message };
		parentSha = initResult.data.commit.sha;
	}

	// 3. Create a blob for every file.
	let blobs: { path: string; mode: '100644'; type: 'blob'; sha: string }[];
	try {
		blobs = await Promise.all(
			files.map(async (f) => {
				const result = await githubRequest<{ sha: string }>(
					token,
					'POST',
					`${repoPath}/git/blobs`,
					{ content: f.content, encoding: 'utf-8' }
				);
				if (!result.ok) throw new Error(`Blob creation failed for ${f.path}: ${result.message}`);
				return {
					path: f.path,
					mode: '100644' as const,
					type: 'blob' as const,
					sha: result.data.sha
				};
			})
		);
	} catch (e) {
		return { error: e instanceof Error ? e.message : 'Blob creation failed' };
	}

	// 4. Create tree with only our files — no base_tree replaces the full tree.
	const treeResult = await githubRequest<{ sha: string }>(token, 'POST', `${repoPath}/git/trees`, {
		tree: blobs
	});
	if (!treeResult.ok) return { error: treeResult.message };

	// 5. Create commit.
	const newCommit = await githubRequest<{ sha: string }>(token, 'POST', `${repoPath}/git/commits`, {
		message: commitMessage,
		tree: treeResult.data.sha,
		parents: parentSha ? [parentSha] : []
	});
	if (!newCommit.ok) return { error: newCommit.message };

	// 6. Update branch ref (force so we can replace the init commit cleanly).
	const update = await githubRequest(
		token,
		'PATCH',
		`${repoPath}/git/refs/heads/${defaultBranch}`,
		{ sha: newCommit.data.sha, force: true }
	);
	if (!update.ok) return { error: (update as { ok: false; message: string }).message };

	return { repoUrl: `https://github.com/${owner}/${repoName}` };
}
