// GitHub REST API helpers — OAuth token exchange + Git Data API bulk push.

const GITHUB_API = 'https://api.github.com';
const USER_AGENT = 'BuilderPro/1.0';

type GithubResult<T> = { ok: true; data: T } | { ok: false; status: number; message: string };

async function githubRequest<T>(
	token: string,
	method: string,
	path: string,
	body?: unknown
): Promise<GithubResult<T>> {
	const res = await fetch(`${GITHUB_API}${path}`, {
		method,
		headers: {
			Authorization: `Bearer ${token}`,
			Accept: 'application/vnd.github+json',
			'X-GitHub-Api-Version': '2022-11-28',
			'Content-Type': 'application/json',
			'User-Agent': USER_AGENT
		},
		...(body !== undefined ? { body: JSON.stringify(body) } : {})
	});

	if (res.ok) {
		// 204 No Content has no body
		const data = res.status === 204 ? ({} as T) : ((await res.json()) as T);
		return { ok: true, data };
	}

	const err = (await res.json().catch(() => ({ message: res.statusText }))) as { message?: string };
	return { ok: false, status: res.status, message: err.message ?? 'GitHub API error' };
}

export function generateOAuthState(): string {
	const bytes = crypto.getRandomValues(new Uint8Array(32));
	return Array.from(bytes)
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
}

/** Exchange an OAuth authorization code for an access token. */
export async function exchangeCode(
	code: string,
	clientId: string,
	clientSecret: string
): Promise<string | null> {
	const res = await fetch('https://github.com/login/oauth/access_token', {
		method: 'POST',
		headers: {
			Accept: 'application/json',
			'Content-Type': 'application/json',
			'User-Agent': USER_AGENT
		},
		body: JSON.stringify({ client_id: clientId, client_secret: clientSecret, code })
	});

	if (!res.ok) return null;
	const data = (await res.json()) as { access_token?: string };
	return data.access_token ?? null;
}

/** Fetch the authenticated GitHub user's login name. */
export async function getGithubUser(token: string): Promise<{ login: string } | null> {
	const result = await githubRequest<{ login: string }>(token, 'GET', '/user');
	return result.ok ? result.data : null;
}

export interface FileContent {
	path: string;
	content: string;
}

/**
 * Push files to a GitHub repo using the Git Data API (single commit, all files at once).
 * Creates the repo if it doesn't exist. Uses force-push semantics — replaces the full tree.
 */
export async function pushFilesToRepo(
	token: string,
	owner: string,
	repoName: string,
	files: FileContent[],
	commitMessage: string
): Promise<{ repoUrl: string } | { error: string }> {
	const repoPath = `/repos/${owner}/${repoName}`;

	// 1. Ensure repo exists — create if 404.
	let defaultBranch: string;
	const repoCheck = await githubRequest<{ default_branch: string }>(token, 'GET', repoPath);
	if (!repoCheck.ok) {
		if (repoCheck.status !== 404) return { error: repoCheck.message };
		const created = await githubRequest<{ default_branch: string }>(token, 'POST', '/user/repos', {
			name: repoName,
			private: false,
			auto_init: false,
			description: `Generated by BuilderPro`
		});
		if (!created.ok) return { error: created.message };
		defaultBranch = created.data.default_branch ?? 'main';
	} else {
		defaultBranch = repoCheck.data.default_branch;
	}

	// 2. Create a blob for every file.
	let blobs: { path: string; mode: '100644'; type: 'blob'; sha: string }[];
	try {
		blobs = await Promise.all(
			files.map(async (f) => {
				const result = await githubRequest<{ sha: string }>(
					token,
					'POST',
					`${repoPath}/git/blobs`,
					{ content: f.content, encoding: 'utf-8' }
				);
				if (!result.ok) throw new Error(`Blob creation failed for ${f.path}: ${result.message}`);
				return {
					path: f.path,
					mode: '100644' as const,
					type: 'blob' as const,
					sha: result.data.sha
				};
			})
		);
	} catch (e) {
		return { error: e instanceof Error ? e.message : 'Blob creation failed' };
	}

	// 3. Resolve current HEAD (may not exist for a brand-new repo).
	let parentSha: string | undefined;
	let baseTreeSha: string | undefined;

	const refResult = await githubRequest<{ object: { sha: string } }>(
		token,
		'GET',
		`${repoPath}/git/refs/heads/${defaultBranch}`
	);
	if (refResult.ok) {
		parentSha = refResult.data.object.sha;
		const commitResult = await githubRequest<{ tree: { sha: string } }>(
			token,
			'GET',
			`${repoPath}/git/commits/${parentSha}`
		);
		if (commitResult.ok) baseTreeSha = commitResult.data.tree.sha;
	}

	// 4. Create tree.
	const treeResult = await githubRequest<{ sha: string }>(token, 'POST', `${repoPath}/git/trees`, {
		tree: blobs,
		...(baseTreeSha ? { base_tree: baseTreeSha } : {})
	});
	if (!treeResult.ok) return { error: treeResult.message };

	// 5. Create commit.
	const newCommit = await githubRequest<{ sha: string }>(token, 'POST', `${repoPath}/git/commits`, {
		message: commitMessage,
		tree: treeResult.data.sha,
		parents: parentSha ? [parentSha] : []
	});
	if (!newCommit.ok) return { error: newCommit.message };

	// 6. Update or create the branch ref.
	if (parentSha) {
		const update = await githubRequest(
			token,
			'PATCH',
			`${repoPath}/git/refs/heads/${defaultBranch}`,
			{
				sha: newCommit.data.sha,
				force: false
			}
		);
		if (!update.ok) return { error: (update as { ok: false; message: string }).message };
	} else {
		const create = await githubRequest(token, 'POST', `${repoPath}/git/refs`, {
			ref: `refs/heads/${defaultBranch}`,
			sha: newCommit.data.sha
		});
		if (!create.ok) return { error: (create as { ok: false; message: string }).message };
	}

	return { repoUrl: `https://github.com/${owner}/${repoName}` };
}
