// GitHub REST API helpers — OAuth token exchange + Git Data API bulk push.
import nacl from 'tweetnacl';
import { blake2b } from '@noble/hashes/blake2.js';

const GITHUB_API = 'https://api.github.com';
const USER_AGENT = 'BuilderPro/1.0';

type GithubResult<T> = { ok: true; data: T } | { ok: false; status: number; message: string };

async function githubRequest<T>(
	token: string,
	method: string,
	path: string,
	body?: unknown
): Promise<GithubResult<T>> {
	const res = await fetch(`${GITHUB_API}${path}`, {
		method,
		headers: {
			Authorization: `Bearer ${token}`,
			Accept: 'application/vnd.github+json',
			'X-GitHub-Api-Version': '2022-11-28',
			'Content-Type': 'application/json',
			'User-Agent': USER_AGENT
		},
		...(body !== undefined ? { body: JSON.stringify(body) } : {})
	});

	if (res.ok) {
		const data = res.status === 204 ? ({} as T) : ((await res.json()) as T);
		return { ok: true, data };
	}

	const err = (await res.json().catch(() => ({ message: res.statusText }))) as { message?: string };
	return { ok: false, status: res.status, message: err.message ?? 'GitHub API error' };
}

export function generateOAuthState(): string {
	const bytes = crypto.getRandomValues(new Uint8Array(32));
	return Array.from(bytes)
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
}

/** Exchange an OAuth authorization code for an access token. */
export async function exchangeCode(
	code: string,
	clientId: string,
	clientSecret: string
): Promise<string | null> {
	const res = await fetch('https://github.com/login/oauth/access_token', {
		method: 'POST',
		headers: {
			Accept: 'application/json',
			'Content-Type': 'application/json',
			'User-Agent': USER_AGENT
		},
		body: JSON.stringify({ client_id: clientId, client_secret: clientSecret, code })
	});

	if (!res.ok) return null;
	const data = (await res.json()) as { access_token?: string };
	return data.access_token ?? null;
}

/** Fetch the authenticated GitHub user's login name. */
export async function getGithubUser(token: string): Promise<{ login: string } | null> {
	const result = await githubRequest<{ login: string }>(token, 'GET', '/user');
	return result.ok ? result.data : null;
}

export interface FileContent {
	path: string;
	content: string;
}

/**
 * Push files to a GitHub repo using the Git Data API (single commit, all files at once).
 * Creates the repo if it doesn't exist. Always replaces the full tree.
 */
export async function pushFilesToRepo(
	token: string,
	owner: string,
	repoName: string,
	files: FileContent[],
	commitMessage: string
): Promise<{ repoUrl: string; commitSha: string } | { error: string }> {
	const repoPath = `/repos/${owner}/${repoName}`;

	// 1. Ensure repo exists — create with auto_init so git storage is ready.
	let defaultBranch: string;
	const repoCheck = await githubRequest<{ default_branch: string }>(token, 'GET', repoPath);
	if (!repoCheck.ok) {
		if (repoCheck.status !== 404) return { error: repoCheck.message };
		const created = await githubRequest<{ default_branch: string }>(token, 'POST', '/user/repos', {
			name: repoName,
			private: false,
			auto_init: true,
			description: 'Generated by BuilderPro'
		});
		if (!created.ok) return { error: created.message };
		defaultBranch = created.data.default_branch ?? 'main';
		await new Promise((r) => setTimeout(r, 1500));
	} else {
		defaultBranch = repoCheck.data.default_branch;
	}

	// 2. Get current HEAD — if repo is empty (no commits yet), initialize via Contents API first.
	let parentSha: string | undefined;
	const headResult = await githubRequest<{ object: { sha: string } }>(
		token,
		'GET',
		`${repoPath}/git/refs/heads/${defaultBranch}`
	);
	if (headResult.ok) {
		parentSha = headResult.data.object.sha;
	} else {
		const initResult = await githubRequest<{ commit: { sha: string } }>(
			token,
			'PUT',
			`${repoPath}/contents/.gitkeep`,
			{ message: 'Initialize repository', content: 'Cg==' }
		);
		if (!initResult.ok) return { error: (initResult as { ok: false; message: string }).message };
		parentSha = initResult.data.commit.sha;
	}

	// 3. Create a blob for every file (utf-8 encoding).
	let blobs: { path: string; mode: '100644'; type: 'blob'; sha: string }[];
	try {
		blobs = await Promise.all(
			files.map(async (f) => {
				const result = await githubRequest<{ sha: string }>(
					token,
					'POST',
					`${repoPath}/git/blobs`,
					{ content: f.content, encoding: 'utf-8' }
				);
				if (!result.ok) throw new Error(`blob:${f.path}: ${result.message}`);
				return { path: f.path, mode: '100644' as const, type: 'blob' as const, sha: result.data.sha };
			})
		);
	} catch (e) {
		return { error: e instanceof Error ? e.message : 'Blob creation failed' };
	}

	// 4. Create tree (no base_tree — replaces entire tree with generated files).
	const treeResult = await githubRequest<{ sha: string }>(token, 'POST', `${repoPath}/git/trees`, {
		tree: blobs
	});
	if (!treeResult.ok) {
		console.error(`[github/push] tree FAILED: ${treeResult.status} ${treeResult.message} owner=${owner} repo=${repoName}`);
		return { error: `[step4-tree:${treeResult.status}] ${treeResult.message}` };
	}

	// 5. Create commit.
	const newCommit = await githubRequest<{ sha: string }>(token, 'POST', `${repoPath}/git/commits`, {
		message: commitMessage,
		tree: treeResult.data.sha,
		parents: parentSha ? [parentSha] : []
	});
	if (!newCommit.ok) return { error: `[step5-commit] ${newCommit.message}` };

	// 6. Update branch ref (force to cleanly replace init commit if needed).
	const update = await githubRequest(
		token,
		'PATCH',
		`${repoPath}/git/refs/heads/${defaultBranch}`,
		{ sha: newCommit.data.sha, force: true }
	);
	if (!update.ok) return { error: `[step6-ref] ${(update as { ok: false; message: string }).message}` };

	return { repoUrl: `https://github.com/${owner}/${repoName}`, commitSha: newCommit.data.sha };
}

/**
 * Enable GitHub Pages on a repo (source = root of default branch).
 * Returns the Pages URL. If Pages is already enabled, fetches the existing URL.
 */
export async function enableGithubPages(
	token: string,
	owner: string,
	repoName: string,
	branch: string
): Promise<{ pagesUrl: string } | { error: string }> {
	const repoPath = `/repos/${owner}/${repoName}`;

	const enable = await githubRequest<{ html_url: string }>(token, 'POST', `${repoPath}/pages`, {
		source: { branch, path: '/' }
	});

	if (enable.ok) return { pagesUrl: enable.data.html_url };

	// 409 = already enabled — fetch current config.
	if ((enable as { ok: false; status: number }).status === 409) {
		const existing = await githubRequest<{ html_url: string }>(token, 'GET', `${repoPath}/pages`);
		if (existing.ok) return { pagesUrl: existing.data.html_url };
		return { error: (existing as { ok: false; message: string }).message };
	}

	return { error: (enable as { ok: false; message: string }).message };
}

/**
 * Register a push webhook on a repo. Returns the webhook ID.
 * Safe to call even if a webhook with the same URL already exists (returns existing id).
 */
export async function registerWebhook(
	token: string,
	owner: string,
	repoName: string,
	webhookUrl: string,
	secret: string
): Promise<{ id: number } | { error: string }> {
	const repoPath = `/repos/${owner}/${repoName}`;

	const result = await githubRequest<{ id: number }>(token, 'POST', `${repoPath}/hooks`, {
		name: 'web',
		active: true,
		events: ['push'],
		config: { url: webhookUrl, content_type: 'json', secret, insecure_ssl: '0' }
	});

	if (result.ok) return { id: result.data.id };

	// 422 = hook with same URL already exists — fetch and return existing id.
	if ((result as { ok: false; status: number }).status === 422) {
		const list = await githubRequest<{ id: number; config: { url: string } }[]>(
			token, 'GET', `${repoPath}/hooks`
		);
		if (list.ok) {
			const existing = list.data.find((h) => h.config.url === webhookUrl);
			if (existing) return { id: existing.id };
		}
	}

	return { error: (result as { ok: false; message: string }).message };
}

/** Verify GitHub webhook HMAC-SHA256 signature (Workers crypto). */
export async function verifyWebhookSignature(
	body: string,
	signature: string,
	secret: string
): Promise<boolean> {
	if (!signature.startsWith('sha256=')) return false;
	const sigHex = signature.slice(7);
	const key = await crypto.subtle.importKey(
		'raw',
		new TextEncoder().encode(secret),
		{ name: 'HMAC', hash: 'SHA-256' },
		false,
		['sign']
	);
	const expected = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(body));
	const expectedHex = Array.from(new Uint8Array(expected))
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
	return expectedHex === sigHex;
}

/** Fetch all files in a repo at a given commit SHA via the Git Tree + Blob API. */
export async function fetchRepoFilesAtCommit(
	token: string,
	owner: string,
	repoName: string,
	commitSha: string
): Promise<FileContent[] | { error: string }> {
	const repoPath = `/repos/${owner}/${repoName}`;

	const treeResult = await githubRequest<{
		tree: { path: string; type: string; sha: string }[];
		truncated: boolean;
	}>(token, 'GET', `${repoPath}/git/trees/${commitSha}?recursive=1`);

	if (!treeResult.ok) return { error: treeResult.message };

	const blobs = treeResult.data.tree.filter(
		(e) => e.type === 'blob' && e.path !== '.gitkeep'
	);

	const files = await Promise.all(
		blobs.map(async (blob) => {
			const blobResult = await githubRequest<{ content: string; encoding: string }>(
				token, 'GET', `${repoPath}/git/blobs/${blob.sha}`
			);
			if (!blobResult.ok) return null;
			const content =
				blobResult.data.encoding === 'base64'
					? atob(blobResult.data.content.replace(/\n/g, ''))
					: blobResult.data.content;
			return { path: blob.path, content };
		})
	);

	return files.filter((f): f is FileContent => f !== null);
}

// ── GitHub Actions Secrets ────────────────────────────────────────────────────

function sealedBox(message: Uint8Array, recipientPk: Uint8Array): Uint8Array {
	const ephKeypair = nacl.box.keyPair();
	// nonce = blake2b(eph_pk || recipient_pk, outputLen=24) — matches libsodium crypto_box_seal
	const nonceInput = new Uint8Array(64);
	nonceInput.set(ephKeypair.publicKey, 0);
	nonceInput.set(recipientPk, 32);
	const nonce = blake2b(nonceInput, { dkLen: 24 });
	const ciphertext = nacl.box(message, nonce, recipientPk, ephKeypair.secretKey);
	const out = new Uint8Array(32 + ciphertext.length);
	out.set(ephKeypair.publicKey, 0);
	out.set(ciphertext, 32);
	return out;
}

function encryptSecret(publicKeyBase64: string, secret: string): string {
	const recipientPk = Uint8Array.from(atob(publicKeyBase64), (c) => c.charCodeAt(0));
	const message = new TextEncoder().encode(secret);
	const encrypted = sealedBox(message, recipientPk);
	return btoa(String.fromCharCode(...encrypted));
}

interface RepoPublicKey {
	key_id: string;
	key: string;
}

/** Set (create or update) a GitHub Actions secret in a repo. */
export async function setRepoSecret(
	token: string,
	owner: string,
	repo: string,
	secretName: string,
	secretValue: string
): Promise<boolean> {
	const pkResult = await githubRequest<RepoPublicKey>(
		token,
		'GET',
		`/repos/${owner}/${repo}/actions/secrets/public-key`
	);
	if (!pkResult.ok) return false;

	const encrypted = encryptSecret(pkResult.data.key, secretValue);
	const result = await githubRequest(token, 'PUT', `/repos/${owner}/${repo}/actions/secrets/${secretName}`, {
		encrypted_value: encrypted,
		key_id: pkResult.data.key_id
	});
	return result.ok;
}

/** Set multiple GitHub Actions secrets. Returns names of secrets that failed. */
export async function setRepoSecrets(
	token: string,
	owner: string,
	repo: string,
	secrets: Record<string, string>
): Promise<string[]> {
	const results = await Promise.all(
		Object.entries(secrets).map(async ([name, value]) => {
			const ok = await setRepoSecret(token, owner, repo, name, value);
			return ok ? null : name;
		})
	);
	return results.filter((r): r is string => r !== null);
}
